spring:
  application:
    name: Darcy-API-dev
  datasource:
    url: jdbc:h2:mem:testdb # or jdbc:h2:file:/~h2db to persist data
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.hibernate: DEBUG